version: "3"
services:
  msu:
    build: .
    image: marvell_msu:1.2
    hostname: msu
    restart: unless-stopped
    volumes:
      - /dev:/dev
      - /srv/docker/marvell:/etc/marvell
    ports:
      - 8845:8845
    device_cgroup_rules:
      - 'c 21:* rmw'
    environment:
      MSU_ROOT_PASSWD: root


